services:
  # main image name
  marketplace-ui:

    # change image name to your dockerhub username and repository name
    image: "marketplace-ui"

    # restart only if the container exits with a non-zero exit code
    restart: on-failure

    # build the production image from the Dockerfile in the current directory
    build:
      context: .
      dockerfile: Dockerfile

    # map port 3000 on the host to port 3000 in the container
    ports:
      - "3000:3000"
