import type { Icon } from '@phosphor-icons/react'
import {
  BabyCarriageIcon,
  BasketballIcon,
  BedIcon,
  BriefcaseIcon,
  BuildingApartmentIcon,
  CarIcon,
  CoatHangerIcon,
  GameControllerIcon,
  GiftIcon,
  HandshakeIcon,
  HouseIcon,
  KeyIcon,
  LaptopIcon,
  PawPrintIcon,
  SparkleIcon,
  SwapIcon,
  TireIcon,
  WrenchIcon,
} from '@phosphor-icons/react/dist/ssr'

export type Category = {
  label: string
  Icon: Icon
  subcategories?: string[]
}

export const categories: Category[] = [
  {
    label: "Children's World",
    Icon: BabyCarriageIcon,
    subcategories: [
      "Children's clothing",
      "Children's footwear",
      'Baby strollers',
      "Children's car seats",
      "Children's furniture",
      'Toys',
      "Children's transport",
      'Feeding & nursing',
      'School supplies',
      "Other children's goods",
    ],
  },
  {
    label: 'Real Estate',
    Icon: BuildingApartmentIcon,
    subcategories: [
      'Apartments',
      'Rooms',
      'Houses',
      'Land',
      'Commercial real estate',
      'Garages & parking',
      'Real estate abroad',
    ],
  },
  {
    label: 'Auto',
    Icon: CarIcon,
    subcategories: [
      'Passenger cars',
      'Trucks',
      'Buses',
      'Motorcycles',
      'Special vehicles',
      'Agricultural machinery',
      'Water transport',
      'Cars from Poland',
      'Trailers / motorhomes',
      'Trucks & special vehicles from Poland',
      'Other transport',
    ],
  },
  {
    label: 'Auto Parts',
    Icon: WrenchIcon,
    subcategories: [
      'Auto parts',
      'Car accessories',
      'Car audio & multimedia',
      'Tires, wheels & rims',
      'GPS navigators / dashcams',
      'Vehicles for parts / dismantling',
      'Motorcycle parts',
      'Motorcycle gear',
      'Motorcycle accessories',
      'Lubricants & car chemicals',
      'Parts for other equipment',
    ],
  },
  {
    label: 'Jobs',
    Icon: BriefcaseIcon,
    subcategories: [
      'Retail / sales / purchasing',
      'Logistics / warehouse / delivery',
      'Construction / finishing works',
      'Call centers / telecommunications',
      'Administrative staff / HR / secretariat',
      'Security / safety',
      'Cleaning / household staff',
      'Beauty / fitness / sports',
      'Education / translation',
      'Culture / art / entertainment',
      'Medicine / pharmaceuticals',
      'IT / computers',
      'Banking / finance / insurance / law',
      'Real estate',
      'Advertising / design / PR',
      'Manufacturing / blue-collar trades',
      'Agriculture / agribusiness',
      'Part-time employment',
      'Career start / students',
      'Work abroad',
      'Accounting',
      'Hotel & restaurant business / tourism',
      'Other fields',
      'Auto repair shops / car washes',
      'Service in the Defense Forces',
    ],
  },
  {
    label: 'Animals',
    Icon: PawPrintIcon,
    subcategories: [
      'Free (animals & breeding)',
      'Dogs',
      'Cats',
      'Aquaristics',
      'Rodents',
      'Farm animals',
      'Other animals',
      'Pet supplies',
      'Breeding',
      'Lost & found',
    ],
  },
  {
    label: 'Home & Garden',
    Icon: HouseIcon,
    subcategories: [
      'Stationery / consumables',
      'Furniture',
      'Food & beverages',
      'Garden / vegetable garden',
      'Interior décor',
      'Construction / renovation',
      'Tools',
      'Indoor plants',
      'Cookware / kitchen utensils',
      'Garden equipment',
      'Household supplies / cleaning products',
      'Other home goods',
    ],
  },
  {
    label: 'Electronics',
    Icon: LaptopIcon,
    subcategories: [
      'Phones & accessories',
      'Computers & components',
      'Photo / video',
      'TV / video equipment',
      'Audio equipment',
      'Games & gaming consoles',
      'Tablets / e-readers & accessories',
      'Laptops & accessories',
      'Home appliances',
      'Kitchen appliances',
      'Climate control equipment',
      'Personal care devices',
      'Accessories & components',
      'Other electronics',
    ],
  },
  {
    label: 'Business & Services',
    Icon: HandshakeIcon,
    subcategories: [
      'Auto / moto services',
      'Beauty / health',
      'Childcare & eldercare',
      'Household services',
      'Cleaning',
      'Education & sports services',
      'Transportation & special equipment services',
      'Photo & video production',
      'Event organization',
      'Equipment repair & maintenance',
      'Construction & renovation',
      'Raw materials / supplies',
      'Recyclables collection',
      'Tourism / immigration',
      'Business services',
      'Business for sale',
      'Business equipment for sale',
      'Services for animals',
      'Funeral services',
      'Other services',
    ],
  },
  {
    label: 'Short-term Rental',
    Icon: BedIcon,
    subcategories: [
      'Houses (daily / hourly)',
      'Apartments (daily / hourly)',
      'Rooms (daily / hourly)',
      'Hotels & resorts',
      'Hostels & bed spaces',
      'Tour operator offers',
    ],
  },
  {
    label: 'Rental & Hire',
    Icon: KeyIcon,
    subcategories: [
      'Transport & special equipment rental',
      'Bicycle & motorcycle rental',
      'Equipment rental',
      'Tool rental',
      'Medical equipment rental',
      'Electronics rental',
      'Event goods rental',
      'Sports & tourist gear rental',
      'Clothing & accessories rental',
      "Children's clothing & goods rental",
      'Other items for rent',
    ],
  },
  {
    label: 'Fashion & Style',
    Icon: CoatHangerIcon,
    subcategories: [
      "Women's clothing",
      "Women's footwear",
      "Men's clothing",
      "Men's footwear",
      "Women's underwear & swimwear",
      "Men's underwear & swimwear",
      'Headwear',
      'Wedding',
      'Wristwatches',
      'Accessories',
      'Maternity clothing',
      'Beauty / health',
      'Gifts',
      'Workwear, work footwear & accessories',
      'Fashion misc',
    ],
  },
  {
    label: 'Hobbies & Sports',
    Icon: BasketballIcon,
    subcategories: [
      'Antiques / collections',
      'Musical instruments',
      'Sport / recreation',
      'Cycling',
      'Militaria',
      'Drones & accessories',
      'Books / magazines',
      'CD / DVD / vinyl records',
      'Tickets',
      'Travel companions',
      'Bands / musicians search',
      'Other',
    ],
  },
  { label: 'Give Away for Free', Icon: GiftIcon },
  { label: 'Exchange / Barter', Icon: SwapIcon },
  { label: 'Famous Finds', Icon: SparkleIcon },
  { label: 'Gaming Products', Icon: GameControllerIcon },
  { label: 'Tires, Discs & Wheels', Icon: TireIcon },
]
