services:
  marketplace-ui:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: "no"
    user: node
    volumes:
      - /usr/app/node_modules
      - .:/usr/app
      - ${HOME}/.ssh:/home/node/.ssh:ro
      - ${HOME}/.gitconfig:/home/node/.gitconfig:ro
